# ***Numpy***
The Basics

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b = np.array([[4, 5, 6], [7, 8, 9]])
print(b)

[[4 5 6]
 [7 8 9]]


In [5]:
a.ndim  #number dimensional array
b.ndim  #number dimensional array

2

In [6]:
a.shape

(3,)

In [7]:
a.dtype

dtype('int64')

In [8]:
a.itemsize

8

In [9]:
a.size

3

**Accessing/Channing sep. ele, rows clo.**

In [14]:
a = np.array([[1,2,3,4,5,6,7],[8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [16]:
a.shape

(2, 7)

In [18]:
print(a[1,-2])

13


In [19]:
print(a[0, :])

[1 2 3 4 5 6 7]


In [21]:
a[:, 2]

array([ 3, 10])

In [24]:
a[0, 1:-1:2]

array([2, 4, 6])

In [27]:
a[1, 5] = 20
print(a)
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [34]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
np.ones((4,3), dtype = 'int32')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [38]:
np.full((2, 2), 4, dtype='float32')

array([[4., 4.],
       [4., 4.]], dtype=float32)

In [41]:
np.full_like(a.shape, 4)

array([4, 4])

In [43]:
np.random.rand(4,2)

array([[0.65178753, 0.24740837],
       [0.62826234, 0.95127623],
       [0.1679481 , 0.41872858],
       [0.74924335, 0.5287255 ]])

In [46]:
np.random.randint(4, size=(4,2))

array([[0, 0],
       [3, 1],
       [1, 0],
       [2, 0]])

In [47]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [54]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [63]:
out = np.ones((5, 5))
print(out)
z = np.zeros((3, 3))
z[1,1] = 9
print(z)
out[1:-1, 1:-1] = z
print(out)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
